import {
  HomeOutlined,
  DeploymentUnitOutlined,
  TagsOutlined,
  CodeOutlined
} from "@ant-design/icons";

export const MENU_ITEMS = [
  { icon: HomeOutlined, path: "/home", name: "home" },
  { icon: DeploymentUnitOutlined, path: "/repositories", name: "repositories" },
  { icon: TagsOutlined, path: "/topics", name: "topics" },
  { icon: CodeOutlined, path: "/commits", name: "commits" },
];

export const NAV_MENUS = [
  {
    icon: 'search-repos',
    path: '/repositories',
    title: 'Search Repositories',
    linkTitle: 'Search Repositories',
    description: 'Search for existing repositories',
  },
  {
    icon: 'search-topics',
    path: '/topics',
    title: 'Search Topics',
    linkTitle: 'Search Topics',
    description: 'Search for existing topics',
  },
  {
    icon: 'search-commits',
    path: '/commits',
    title: 'Search for commits',
    linkTitle: 'Search commits',
    description: 'Search for commits',
  },
];


export const REPO_DATA = [
  {
    "id": 60782323,
    "node_id": "MDEwOlJlcG9zaXRvcnk2MDc4MjMyMw==",
    "name": "smartmover",
    "full_name": "andrewacampbell/smartmover",
    "private": false,
    "owner": {
      "login": "andrewacampbell",
      "id": 7964196,
      "node_id": "MDQ6VXNlcjc5NjQxOTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7964196?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/andrewacampbell",
      "html_url": "https://github.com/andrewacampbell",
      "followers_url": "https://api.github.com/users/andrewacampbell/followers",
      "following_url": "https://api.github.com/users/andrewacampbell/following{/other_user}",
      "gists_url": "https://api.github.com/users/andrewacampbell/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/andrewacampbell/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/andrewacampbell/subscriptions",
      "organizations_url": "https://api.github.com/users/andrewacampbell/orgs",
      "repos_url": "https://api.github.com/users/andrewacampbell/repos",
      "events_url": "https://api.github.com/users/andrewacampbell/events{/privacy}",
      "received_events_url": "https://api.github.com/users/andrewacampbell/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/andrewacampbell/smartmover",
    "description": "Get from user the city and state they are moving to, it then return data base on the user input. It give information about a place you are planning to move to in NewYork Times and wiki articles, and change the background also. ",
    "fork": false,
    "url": "https://api.github.com/repos/andrewacampbell/smartmover",
    "forks_url": "https://api.github.com/repos/andrewacampbell/smartmover/forks",
    "keys_url": "https://api.github.com/repos/andrewacampbell/smartmover/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/andrewacampbell/smartmover/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/andrewacampbell/smartmover/teams",
    "hooks_url": "https://api.github.com/repos/andrewacampbell/smartmover/hooks",
    "issue_events_url": "https://api.github.com/repos/andrewacampbell/smartmover/issues/events{/number}",
    "events_url": "https://api.github.com/repos/andrewacampbell/smartmover/events",
    "assignees_url": "https://api.github.com/repos/andrewacampbell/smartmover/assignees{/user}",
    "branches_url": "https://api.github.com/repos/andrewacampbell/smartmover/branches{/branch}",
    "tags_url": "https://api.github.com/repos/andrewacampbell/smartmover/tags",
    "blobs_url": "https://api.github.com/repos/andrewacampbell/smartmover/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/andrewacampbell/smartmover/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/andrewacampbell/smartmover/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/andrewacampbell/smartmover/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/andrewacampbell/smartmover/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/andrewacampbell/smartmover/languages",
    "stargazers_url": "https://api.github.com/repos/andrewacampbell/smartmover/stargazers",
    "contributors_url": "https://api.github.com/repos/andrewacampbell/smartmover/contributors",
    "subscribers_url": "https://api.github.com/repos/andrewacampbell/smartmover/subscribers",
    "subscription_url": "https://api.github.com/repos/andrewacampbell/smartmover/subscription",
    "commits_url": "https://api.github.com/repos/andrewacampbell/smartmover/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/andrewacampbell/smartmover/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/andrewacampbell/smartmover/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/andrewacampbell/smartmover/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/andrewacampbell/smartmover/contents/{+path}",
    "compare_url": "https://api.github.com/repos/andrewacampbell/smartmover/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/andrewacampbell/smartmover/merges",
    "archive_url": "https://api.github.com/repos/andrewacampbell/smartmover/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/andrewacampbell/smartmover/downloads",
    "issues_url": "https://api.github.com/repos/andrewacampbell/smartmover/issues{/number}",
    "pulls_url": "https://api.github.com/repos/andrewacampbell/smartmover/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/andrewacampbell/smartmover/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/andrewacampbell/smartmover/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/andrewacampbell/smartmover/labels{/name}",
    "releases_url": "https://api.github.com/repos/andrewacampbell/smartmover/releases{/id}",
    "deployments_url": "https://api.github.com/repos/andrewacampbell/smartmover/deployments",
    "created_at": "2016-06-09T14:46:10Z",
    "updated_at": "2016-07-18T10:19:48Z",
    "pushed_at": "2016-06-25T19:55:28Z",
    "git_url": "git://github.com/andrewacampbell/smartmover.git",
    "ssh_url": "git@github.com:andrewacampbell/smartmover.git",
    "clone_url": "https://github.com/andrewacampbell/smartmover.git",
    "svn_url": "https://github.com/andrewacampbell/smartmover",
    "homepage": "",
    "size": 37,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    },
    "score": 1.0
  },
  {
    "id": 558591267,
    "node_id": "R_kgDOIUttIw",
    "name": "smartmovers",
    "full_name": "DynastyG/smartmovers",
    "private": false,
    "owner": {
      "login": "DynastyG",
      "id": 86953869,
      "node_id": "MDQ6VXNlcjg2OTUzODY5",
      "avatar_url": "https://avatars.githubusercontent.com/u/86953869?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DynastyG",
      "html_url": "https://github.com/DynastyG",
      "followers_url": "https://api.github.com/users/DynastyG/followers",
      "following_url": "https://api.github.com/users/DynastyG/following{/other_user}",
      "gists_url": "https://api.github.com/users/DynastyG/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DynastyG/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DynastyG/subscriptions",
      "organizations_url": "https://api.github.com/users/DynastyG/orgs",
      "repos_url": "https://api.github.com/users/DynastyG/repos",
      "events_url": "https://api.github.com/users/DynastyG/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DynastyG/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/DynastyG/smartmovers",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/DynastyG/smartmovers",
    "forks_url": "https://api.github.com/repos/DynastyG/smartmovers/forks",
    "keys_url": "https://api.github.com/repos/DynastyG/smartmovers/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/DynastyG/smartmovers/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/DynastyG/smartmovers/teams",
    "hooks_url": "https://api.github.com/repos/DynastyG/smartmovers/hooks",
    "issue_events_url": "https://api.github.com/repos/DynastyG/smartmovers/issues/events{/number}",
    "events_url": "https://api.github.com/repos/DynastyG/smartmovers/events",
    "assignees_url": "https://api.github.com/repos/DynastyG/smartmovers/assignees{/user}",
    "branches_url": "https://api.github.com/repos/DynastyG/smartmovers/branches{/branch}",
    "tags_url": "https://api.github.com/repos/DynastyG/smartmovers/tags",
    "blobs_url": "https://api.github.com/repos/DynastyG/smartmovers/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/DynastyG/smartmovers/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/DynastyG/smartmovers/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/DynastyG/smartmovers/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/DynastyG/smartmovers/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/DynastyG/smartmovers/languages",
    "stargazers_url": "https://api.github.com/repos/DynastyG/smartmovers/stargazers",
    "contributors_url": "https://api.github.com/repos/DynastyG/smartmovers/contributors",
    "subscribers_url": "https://api.github.com/repos/DynastyG/smartmovers/subscribers",
    "subscription_url": "https://api.github.com/repos/DynastyG/smartmovers/subscription",
    "commits_url": "https://api.github.com/repos/DynastyG/smartmovers/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/DynastyG/smartmovers/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/DynastyG/smartmovers/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/DynastyG/smartmovers/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/DynastyG/smartmovers/contents/{+path}",
    "compare_url": "https://api.github.com/repos/DynastyG/smartmovers/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/DynastyG/smartmovers/merges",
    "archive_url": "https://api.github.com/repos/DynastyG/smartmovers/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/DynastyG/smartmovers/downloads",
    "issues_url": "https://api.github.com/repos/DynastyG/smartmovers/issues{/number}",
    "pulls_url": "https://api.github.com/repos/DynastyG/smartmovers/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/DynastyG/smartmovers/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/DynastyG/smartmovers/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/DynastyG/smartmovers/labels{/name}",
    "releases_url": "https://api.github.com/repos/DynastyG/smartmovers/releases{/id}",
    "deployments_url": "https://api.github.com/repos/DynastyG/smartmovers/deployments",
    "created_at": "2022-10-27T21:35:38Z",
    "updated_at": "2024-05-22T02:04:21Z",
    "pushed_at": "2022-10-27T21:36:37Z",
    "git_url": "git://github.com/DynastyG/smartmovers.git",
    "ssh_url": "git@github.com:DynastyG/smartmovers.git",
    "clone_url": "https://github.com/DynastyG/smartmovers.git",
    "svn_url": "https://github.com/DynastyG/smartmovers",
    "homepage": null,
    "size": 1131,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    },
    "score": 1.0
  },
  {
    "id": 450440618,
    "node_id": "R_kgDOGtktqg",
    "name": "smartmovers",
    "full_name": "Aljaaiz/smartmovers",
    "private": false,
    "owner": {
      "login": "Aljaaiz",
      "id": 22438524,
      "node_id": "MDQ6VXNlcjIyNDM4NTI0",
      "avatar_url": "https://avatars.githubusercontent.com/u/22438524?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Aljaaiz",
      "html_url": "https://github.com/Aljaaiz",
      "followers_url": "https://api.github.com/users/Aljaaiz/followers",
      "following_url": "https://api.github.com/users/Aljaaiz/following{/other_user}",
      "gists_url": "https://api.github.com/users/Aljaaiz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Aljaaiz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Aljaaiz/subscriptions",
      "organizations_url": "https://api.github.com/users/Aljaaiz/orgs",
      "repos_url": "https://api.github.com/users/Aljaaiz/repos",
      "events_url": "https://api.github.com/users/Aljaaiz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Aljaaiz/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Aljaaiz/smartmovers",
    "description": "Real Estate Move in Move out Application",
    "fork": false,
    "url": "https://api.github.com/repos/Aljaaiz/smartmovers",
    "forks_url": "https://api.github.com/repos/Aljaaiz/smartmovers/forks",
    "keys_url": "https://api.github.com/repos/Aljaaiz/smartmovers/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Aljaaiz/smartmovers/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Aljaaiz/smartmovers/teams",
    "hooks_url": "https://api.github.com/repos/Aljaaiz/smartmovers/hooks",
    "issue_events_url": "https://api.github.com/repos/Aljaaiz/smartmovers/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Aljaaiz/smartmovers/events",
    "assignees_url": "https://api.github.com/repos/Aljaaiz/smartmovers/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Aljaaiz/smartmovers/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Aljaaiz/smartmovers/tags",
    "blobs_url": "https://api.github.com/repos/Aljaaiz/smartmovers/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Aljaaiz/smartmovers/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Aljaaiz/smartmovers/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Aljaaiz/smartmovers/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Aljaaiz/smartmovers/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Aljaaiz/smartmovers/languages",
    "stargazers_url": "https://api.github.com/repos/Aljaaiz/smartmovers/stargazers",
    "contributors_url": "https://api.github.com/repos/Aljaaiz/smartmovers/contributors",
    "subscribers_url": "https://api.github.com/repos/Aljaaiz/smartmovers/subscribers",
    "subscription_url": "https://api.github.com/repos/Aljaaiz/smartmovers/subscription",
    "commits_url": "https://api.github.com/repos/Aljaaiz/smartmovers/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Aljaaiz/smartmovers/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Aljaaiz/smartmovers/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Aljaaiz/smartmovers/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Aljaaiz/smartmovers/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Aljaaiz/smartmovers/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Aljaaiz/smartmovers/merges",
    "archive_url": "https://api.github.com/repos/Aljaaiz/smartmovers/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Aljaaiz/smartmovers/downloads",
    "issues_url": "https://api.github.com/repos/Aljaaiz/smartmovers/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Aljaaiz/smartmovers/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Aljaaiz/smartmovers/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Aljaaiz/smartmovers/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Aljaaiz/smartmovers/labels{/name}",
    "releases_url": "https://api.github.com/repos/Aljaaiz/smartmovers/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Aljaaiz/smartmovers/deployments",
    "created_at": "2022-01-21T10:04:58Z",
    "updated_at": "2022-01-21T10:36:52Z",
    "pushed_at": "2022-02-13T03:45:31Z",
    "git_url": "git://github.com/Aljaaiz/smartmovers.git",
    "ssh_url": "git@github.com:Aljaaiz/smartmovers.git",
    "clone_url": "https://github.com/Aljaaiz/smartmovers.git",
    "svn_url": "https://github.com/Aljaaiz/smartmovers",
    "homepage": null,
    "size": 40002,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "PHP",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    },
    "score": 1.0
  }
]